server:
  port: 8002
spring:
  application:
    name: spring-cloud-config-client
  ## 开启消息跟踪
  cloud:
    bus:
      trace:
        enabled: true
  rabbitmq:
    host: 106.14.116.180
    port: 5672
    username: admin
    password: 123456
  zipkin:
    base-url: http://localhost:9009
  sleuth:
    sampler:
      percentage: 1.0

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh