server:
  port: 8002
spring:
  application:
    name: spring-cloud-config-client
  ## 开启消息跟踪
  cloud:
    bus:
      trace:
        enabled: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: 123456

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh