server:
  port: 9009
spring:
  application:
    name: spring-cloud-zipkin-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
management:
  metrics:
    web:
      server:
        auto-time-requests: false